name: ci

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".editorconfig"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - ".editorconfig"

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install global @vue/cli
        run: npm install -g @vue/cli@5.0.0-rc.1

      - name: Install package dependencies
        run: npm ci

      - name: Build dist files
        run: npm run build

      - name: Lint project
        run: npm run lint

      - name: Run unit tests
        run: npm run test
