name: ci

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "*.md"
      - ".editorconfig"
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "*.md"
      - ".editorconfig"
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Cache node_modules
        uses: actions/cache@v4
        id: cache-npm
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install package dependencies
        run: npm install

      - name: Build dist files
        run: npm run build

      - name: Lint project
        run: npm run lint

      - name: Run unit tests
        run: npm run test --if-present
